apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: 647198474080.dkr.ecr.us-east-1.amazonaws.com/strapi-artifacts:0345b7273965df3199bc57015beb1e8935917d34
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: "sqlite"
