apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  labels:
    app: strapi
spec:
  type: NodePort
  selector:
    app: strapi
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
      nodePort: 30080  # You can access it via <EC2-IP>:30080
